### PR TITLE
Add dummy stub for rpmem server engine

### PR DESCRIPTION
**Pull request by karczex**
Currently  *unused variable* warning occure during build

---
This change is [Reviewable](https://reviewable.io/reviews/janekmi/fio/2)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex)

___
*[Makefile, line 106 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCY6WY6YJ463SMpg0E:-MHCY6WY6YJ463SMpg0F:b98zj6x) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/Makefile#L106)):*
> ```Makefile
>   librpma_LIBS = -libverbs -lrdmacm -lrpma
>   ENGINES += librpma_server
> endif
> ```

Please join with the previous ifdef-statement.
___
*[engines/librpma_server.c, line 20 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCZMT97ErVyrqxZ_SK:-MHCZMT97ErVyrqxZ_SL:b-s3hmk9) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L20)):*
> ```C
> #include <librpma.h>
> 
> #define FIO_RDMA_MAX_IO_DEPTH    512
> ```

Not needed.
___
*[engines/librpma_server.c, line 61 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCYQWjEjah8WRiOa-R:-MHCYQWjEjah8WRiOa-S:b-s3hmjs) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L61)):*
> ```C
> 		.category = FIO_OPT_C_ENGINE,
> 		.group	= FIO_OPT_G_LIBRPMA,
> 	},
> ```

Not needed?
___
*[engines/librpma_server.c, line 72 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCYSst6vAIJ467USGg:-MHCYSst6vAIJ467USGh:b-s3hmk9) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L72)):*
> ```C
> 	uint32_t rkey;
> 	uint32_t size;
> };
> ```

Not needed.
___
*[engines/librpma_server.c, line 81 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCYV7cAD-7ypxbs82n:-MHCYV7cAD-7ypxbs82o:b-s3hmk9) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L81)):*
> ```C
> 	uint32_t max_bs;        /* maximum block size */
> 	struct remote_u rmt_us[FIO_RDMA_MAX_IO_DEPTH];
> };
> ```

Not needed.
___
*[engines/librpma_server.c, line 171 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCYj5HCQUVs_RNYGLn:-MHCYj5HCQUVs_RNYGLo:bd4z025) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L171)):*
> ```C
> 
> FIO_STATIC struct ioengine_ops ioengine = {
> 	.name			= "librpma_srv",
> ```

svr-> server.

Please apply consistently.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: all files reviewed, 7 unresolved discussions (waiting on @karczex)

___
*[engines/librpma_server.c, line 37 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHDBQ_G2ZTCoyvPX5qM:-MHDBQ_HDtgfCQvaarlD:b-mrv851) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L37)):*
> ```C
> 		.off1	= offsetof(struct librpma_srvio_options, listen_ip),
> 		.help	= "ip of server engine",
> 		.def    = "127.0.0.1",
> ```

This will never work with SoftRoCE.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[Makefile, line 106 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCY6WY6YJ463SMpg0E:-MHFQOa9-qMDt2HGhd5u:b-896fix) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/Makefile#L106)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please join with the previous ifdef-statement.
</blockquote></details>

Done.
___
*[engines/librpma_server.c, line 20 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCZMT97ErVyrqxZ_SK:-MHFQVbd4ZtF_618E9zs:b-896fix) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[engines/librpma_server.c, line 37 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHDBQ_G2ZTCoyvPX5qM:-MHFTLqC-55x7XUjnXWo:b-896fix) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

This will never work with SoftRoCE. 
</blockquote></details>

Done.
___
*[engines/librpma_server.c, line 61 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCYQWjEjah8WRiOa-R:-MHFTLKy02fWUSnUMBki:b-896fix) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L61)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed?
</blockquote></details>

Done.
___
*[engines/librpma_server.c, line 72 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCYSst6vAIJ467USGg:-MHFQvRZ2BukaEaNxW1Z:b-896fix) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L72)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[engines/librpma_server.c, line 81 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCYV7cAD-7ypxbs82n:-MHFQvl5D41Lpn3pk2fr:b-896fix) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[engines/librpma_server.c, line 171 at r1](https://reviewable.io/reviews/janekmi/fio/2#-MHCYj5HCQUVs_RNYGLn:-MHFTOzD7-7kmncubWCv:b-896fix) ([raw file](https://github.com/janekmi/fio/blob/1ad1fe0064350319790bbdc67602cd110f154f76/engines/librpma_server.c#L171)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

svr-> server.

Please apply consistently.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @karczex)

___
*[engines/librpma_server.c, line 4 at r3](https://reviewable.io/reviews/janekmi/fio/2#-MHF_ZEU3YjiReRoc6zh:-MHF_ZEU3YjiReRoc6zi:bj41kkk) ([raw file](https://github.com/janekmi/fio/blob/66e73556c55622a4a57f66b1ff8e84f758b19aea/engines/librpma_server.c#L4)):*
> ```C
>  * librpma_server I/O engine
>  *
>  * librpma_server engine should be used together with librpma_clinet engine
> ```

`should be used with librpma engine`

do we plan to change the name of the original (client) file?
___
*[engines/librpma_server.c, line 21 at r3](https://reviewable.io/reviews/janekmi/fio/2#-MHF_vKo0ydgX9mNqNqa:-MHF_vKo0ydgX9mNqNqb:b-o409sj) ([raw file](https://github.com/janekmi/fio/blob/66e73556c55622a4a57f66b1ff8e84f758b19aea/engines/librpma_server.c#L21)):*
> ```C
> 
> 
> struct librpma_server_io_options {
> ```

perhaps rename to `fio_librpmaio_server_options` to be consistent with the other engine

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2#-:-MHFbDtB3-CtMe_AFr6m:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @karczex, and @lukaszstolarczuk)

___
*[engines/librpma_server.c, line 4 at r3](https://reviewable.io/reviews/janekmi/fio/2#-MHF_ZEU3YjiReRoc6zh:-MHFb41D5RZUKAJG9pzQ:bswogkw) ([raw file](https://github.com/janekmi/fio/blob/66e73556c55622a4a57f66b1ff8e84f758b19aea/engines/librpma_server.c#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`should be used with librpma engine`

do we plan to change the name of the original (client) file?
</blockquote></details>

I just wanted to ask you to do this in the next step. x-D

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @lukaszstolarczuk)

___
*[engines/librpma_server.c, line 4 at r3](https://reviewable.io/reviews/janekmi/fio/2#-MHF_ZEU3YjiReRoc6zh:-MHFcaIT65vI2gyaLlns:b-v6jq5f) ([raw file](https://github.com/janekmi/fio/blob/66e73556c55622a4a57f66b1ff8e84f758b19aea/engines/librpma_server.c#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I just wanted to ask you to do this in the next step. x-D
</blockquote></details>

somehow Done. 
___
*[engines/librpma_server.c, line 21 at r3](https://reviewable.io/reviews/janekmi/fio/2#-MHF_vKo0ydgX9mNqNqa:-MHFc_z35_YL-B2zh-ft:b-896fix) ([raw file](https://github.com/janekmi/fio/blob/66e73556c55622a4a57f66b1ff8e84f758b19aea/engines/librpma_server.c#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps rename to `fio_librpmaio_server_options` to be consistent with the other engine
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @karczex, and @lukaszstolarczuk)

___
*[engines/librpma_server.c, line 4 at r4](https://reviewable.io/reviews/janekmi/fio/2#-MHFfpgk4vMqI13Y-LLI:-MHFfpglCHQLMWO-ozjL:b-2i2g3q) ([raw file](https://github.com/janekmi/fio/blob/f223a95a8a828946fc98a25fdac714b83ac3100c/engines/librpma_server.c#L4)):*
> ```C
>  * librpma_server I/O engine
>  *
>  * librpma_server engine should be used together with librpma_clinet engine
> ```

librpma_clinet - misspell

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @karczex)

___
*[engines/librpma_server.c, line 21 at r3](https://reviewable.io/reviews/janekmi/fio/2#-MHF_vKo0ydgX9mNqNqa:-MHFgFhW3JSOxlVmpDG7:bv3tx1a) ([raw file](https://github.com/janekmi/fio/blob/66e73556c55622a4a57f66b1ff8e84f758b19aea/engines/librpma_server.c#L21)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

Done.
</blockquote></details>

fio_librpma_server_options

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @lukaszstolarczuk)

___
*[engines/librpma_server.c, line 4 at r4](https://reviewable.io/reviews/janekmi/fio/2#-MHFfpgk4vMqI13Y-LLI:-MHFhY5w1dYR2jYt8FGa:b-896fix) ([raw file](https://github.com/janekmi/fio/blob/f223a95a8a828946fc98a25fdac714b83ac3100c/engines/librpma_server.c#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

librpma_clinet - misspell
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2#-:-MHFiICl6xNr46X8uxzf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/2)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
