### PR TITLE
rpma: iomem_init and _free

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/janekmi/fio/7)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/7)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_server.c, line 175 at r1](https://reviewable.io/reviews/janekmi/fio/7#-MHG9N94BfndGo-66tGt:-MHG9N9558iy7H_QLM_E:bgcgvs6) ([raw file](https://github.com/janekmi/fio/blob/43f84ed0778e40c08723b218b2a87d29f3064c47/engines/librpma_server.c#L175)):*
> ```C
> 
> 	/* deregister the memory region */
> 	if ((ret = rpma_mr_dereg(&rd->mr_local))) {
> ```

shouldn't we check if `mr_local` is initialized?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/7)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[engines/librpma_server.c, line 175 at r1](https://reviewable.io/reviews/janekmi/fio/7#-MHG9N94BfndGo-66tGt:-MHGAvMR98GjQKzdtQP9:b-9036k7) ([raw file](https://github.com/janekmi/fio/blob/43f84ed0778e40c08723b218b2a87d29f3064c47/engines/librpma_server.c#L175)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't we check if `mr_local` is initialized?
</blockquote></details>

If `mr_local == NULL` it will return with success. So it doesn't matter I believe.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/7#-:-MHGBZRcC5aZ16GhmocS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/7#-:-MHGCenR8tNtAz6K_Rge:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
