### PR TITLE
rpma: init client

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/janekmi/fio/9)

### CODE REVIEW

**Comment by karczex** [comment]
___
*[engines/librpma_client.c, line 1151 at r1](https://reviewable.io/reviews/janekmi/fio/9#-MHGH5pv1SOY1GaIvqIL:-MHGH5pv1SOY1GaIvqIM:b-pgvr23) ([raw file](https://github.com/janekmi/fio/blob/101b67d88cdc3a527abc57a43e7d74d0493107c6/engines/librpma_client.c#L1151)):*
> ```C
> 	pdata.ptr = (void *)msg;
> 	pdata.len = (strlen(msg) + 1) * sizeof(char);
> 	ret = rpma_conn_req_connect(&req, &pdata, &rd->conn);
> ```

If I understand correctly, at this point pdata may be NULL, and msg variable (and  is not needed. 

as called here: 
(https://github.com/pmem/rpma/blob/eebd0edf4d0ce08360a2a25b4db93507f9275906/examples/02-read-to-volatile/client.c#L77)  

https://github.com/pmem/rpma/blob/eebd0edf4d0ce08360a2a25b4db93507f9275906/examples/common/common-conn.c#L59

and later call  rpma_conn_get_private_data(conn, &pdata);

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[engines/librpma_client.c, line 1151 at r1](https://reviewable.io/reviews/janekmi/fio/9#-MHGH5pv1SOY1GaIvqIL:-MHGHjtgDbYLTXLalMpQ:b8w1b69) ([raw file](https://github.com/janekmi/fio/blob/101b67d88cdc3a527abc57a43e7d74d0493107c6/engines/librpma_client.c#L1151)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

If I understand correctly, at this point pdata may be NULL, and msg variable (and  is not needed. 

as called here: 
(https://github.com/pmem/rpma/blob/eebd0edf4d0ce08360a2a25b4db93507f9275906/examples/02-read-to-volatile/client.c#L77)  

https://github.com/pmem/rpma/blob/eebd0edf4d0ce08360a2a25b4db93507f9275906/examples/common/common-conn.c#L59

and later call  rpma_conn_get_private_data(conn, &pdata); 
</blockquote></details>

You are right. The server does not need client's memory. Sec.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[engines/librpma_client.c, line 1151 at r1](https://reviewable.io/reviews/janekmi/fio/9#-MHGH5pv1SOY1GaIvqIL:-MHGIDdz5Oaft46v9hBF:b-896fix) ([raw file](https://github.com/janekmi/fio/blob/101b67d88cdc3a527abc57a43e7d74d0493107c6/engines/librpma_client.c#L1151)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are right. The server does not need client's memory. Sec.
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/janekmi/fio/9#-:-MHGIhNA-bfSGWRdrG89:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
